# Generated by Django 3.2.4 on 2021-07-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subtitle', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('right_subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/%Y%m%d/')),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='BAŞLIK')),
                ('name', models.CharField(max_length=100, verbose_name='AD')),
                ('last_name', models.CharField(max_length=100, verbose_name='SOYAD')),
                ('image', models.ImageField(upload_to='media/%Y%m%d/')),
                ('description', models.TextField()),
                ('proverb', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/%Y%m%d/', verbose_name='Proje Kapak Fotoğrafı')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=25)),
                ('image_title', models.CharField(max_length=100, verbose_name='Resim Başlığı')),
                ('image_SS', models.ImageField(upload_to='post/%Y%m%d/', verbose_name='Projenin Ekran Görüntüsü')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
