# Generated by Django 3.2.4 on 2021-07-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sub_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='sub_description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='sub_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='subject_image',
            field=models.ImageField(default='neW', upload_to='media/%Y%m%d/'),
            preserve_default=False,
        ),
    ]
