# Generated by Django 3.2.4 on 2021-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210722_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sub_description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='sub_title1',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='subject_image1',
            field=models.ImageField(default='1d1', upload_to='media/%Y%m%d/'),
            preserve_default=False,
        ),
    ]
