# Generated by Django 3.2.4 on 2021-07-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210722_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='sub_description2',
            new_name='sub_des1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='sub_description3',
            new_name='sub_des3',
        ),
    ]
