# Generated by Django 3.2.4 on 2021-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210722_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='proverb1',
            field=models.CharField(default='yes', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='proverb2',
            field=models.CharField(default='yes', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='sub_desc1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='sub_desc3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
