# Generated by Django 3.2.4 on 2021-07-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210722_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='g', upload_to='post/%Y%m%d/', verbose_name='BÜYÜK RESİMLER'),
            preserve_default=False,
        ),
    ]
