# Generated by Django 3.2.4 on 2021-07-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210723_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default="Hi I'm Mert ÇALIŞKAN", max_length=100),
            preserve_default=False,
        ),
    ]
