# Generated by Django 3.2.4 on 2021-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_1',
            field=models.ImageField(default='resim', upload_to=''),
            preserve_default=False,
        ),
    ]
