# Generated by Django 3.2.4 on 2021-07-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_about_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='proverb1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='proverb2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_des1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_des3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_desc1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_desc3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_title1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_title2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='subject_image1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='subject_image2',
        ),
    ]
