# Generated by Django 3.2.4 on 2021-07-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210726_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='sub_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_description1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_title',
        ),
    ]
