# Generated by Django 3.2.4 on 2021-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210726_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media/%Y%m%d/'),
        ),
    ]
